services:
  db:
    image: mariadb:11.7
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: messi
      MARIADB_USER: aditya
      MARIADB_PASSWORD: deptech
      MARIADB_DATABASE: deptech
    volumes:
      - ./docker-data/mariadb:/var/lib/mysql
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: aditya
      MINIO_ROOT_PASSWORD: deptech
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker-data/minio:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env.docker
  #   depends_on:
  #     - db
  #   restart: unless-stopped